# Generated by Django 5.2.7 on 2025-12-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='competitions/'),
        ),
    ]
