# Generated by Django 5.2.7 on 2025-12-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_group_teams_teamgroup_teamseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('name', 'competition', 'url')},
        ),
    ]
