# Generated by Django 5.2.7 on 2025-12-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_season_url_alter_season_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgroup',
            name='hero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='hero',
            field=models.BooleanField(default=False),
        ),
    ]
