# Generated by Django 5.2.7 on 2025-12-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_teamgroup_hero_teamseason_hero'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seasonteam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seasonteam',
            name='against',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seasonteam',
            name='difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonteam',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonteam',
            name='hero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seasonteam',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonteam',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonteam',
            name='won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasonteam',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.season'),
        ),
        migrations.AlterField(
            model_name='seasonteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.DeleteModel(
            name='TeamSeason',
        ),
        migrations.RemoveField(
            model_name='seasonteam',
            name='position',
        ),
    ]
