# Generated by Django 5.2.7 on 2025-12-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_seasonteam_unique_together_seasonteam_against_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamGroup',
            new_name='GroupTeam',
        ),
    ]
